INSERT INTO utente VALUES('1','Nome1','Cognome1','email1@gmail.com','utente1','pass1','3457338287','Via Miraglia','12','89132','Reggio Calabria','RC',false);
INSERT INTO utente VALUES('2','Nome2','Cognome2','email2@gmail.com','utente2','pass2','368651290','Via Novara','4','10045','Firenze','FI',false);
INSERT INTO utente VALUES('3','Nome3','Cognome3','email3@gmail.com','utente3','pass3','3206499032','Via Lia','7','23456','Napoli','NA',false);
INSERT INTO utente VALUES('4','Nome4','Cognome4','email4@gmail.com','utente4','pass4','3450766453','Via Santa Caterina','78','23098','Roma','RM',false);

INSERT INTO piattaforma VALUES('1','PC');
INSERT INTO piattaforma VALUES('2','PlayStation');
INSERT INTO piattaforma VALUES('3','xBox');
INSERT INTO piattaforma VALUES('4','Nintendo');

INSERT INTO genere VALUES('1','FPS');
INSERT INTO genere VALUES('3','VR');
INSERT INTO genere VALUES('4','AVVENTURA');
INSERT INTO genere VALUES('5','GUIDA');
INSERT INTO genere VALUES('6','RPG');
INSERT INTO genere VALUES('7','AZIONE');
INSERT INTO genere VALUES('8','ALTRO');
INSERT INTO genere VALUES('9','SIMULAZIONE');

INSERT INTO sviluppatore VALUES('1','Riot');
INSERT INTO sviluppatore VALUES('2','Rockstar');
INSERT INTO sviluppatore VALUES('3','Ubisoft');
INSERT INTO sviluppatore VALUES('4','EA');
INSERT INTO sviluppatore VALUES('5','Naughty Dog');
INSERT INTO sviluppatore VALUES('6','Milestone S.r.l.');
INSERT INTO sviluppatore VALUES('7','Gunfire Games');
INSERT INTO sviluppatore VALUES('8','NetherRealm Studios');
INSERT INTO sviluppatore VALUES('9','Sony Interactive Entertainment');
INSERT INTO sviluppatore VALUES('10','Santa Monica Studio');
INSERT INTO sviluppatore VALUES('11','Playgroud Studios');
INSERT INTO sviluppatore VALUES('12','Blizzard Entertainment');
INSERT INTO sviluppatore VALUES('13','Toys For Bob');
INSERT INTO sviluppatore VALUES('14','Nintendo');
INSERT INTO sviluppatore VALUES('15','Deep Silver Dambuster Studios');
INSERT INTO sviluppatore VALUES('16','Tindalos Interactive');
INSERT INTO sviluppatore VALUES('17','Tobyfox');

INSERT INTO gioco VALUES('1','Undertale',"Benvenuti in UNDERTALE. In questo gioco di ruolo, controlli un essere umano che cade sottoterra nel mondo dei mostri. Ora devi trovare la via d'uscita... o rimarrai intrappolato per sempre. ((Healthy Dog's Warning: il gioco contiene immagini che potrebbero essere dannose per i giocatori con epilessia fotosensibile o condizioni simili.)) caratteristiche: Uccidere non è necessario: negoziare fuori pericolo utilizzando l'esclusivo sistema di battaglia.",'9.99','2015-09-15','https://gaming-cdn.com/img/products/4986/pcover/4986.jpg?v=1608049517','https://gaming-cdn.com/images/products/4986/616x353/gioco-steam-undertale-cover.jpg?v=1608049517','1','6','17');
INSERT INTO gioco VALUES('2','MotoGP 23',"Dai gas, sorpassa i tuoi avversari e taglia il traguardo: vivi il sogno di essere il prossimo campione con il nuovo MotoGP23, più sorprendente e sfidante che mai!Scegli tra le tre categorie ufficiali MotoGP, Moto2 e Moto3, vesti i panni del tuo pilota preferito e scendi in pista per vivere l'adrenalina della stagione 2023.",'50.99','2023-06-08','https://gaming-cdn.com/img/products/13416/pcover/1400x500/13416.jpg?v=1686308549','https://gaming-cdn.com/images/products/13416/616x353/motogp-23-pc-gioco-steam-cover.jpg?v=1686308549','1','5','6');
INSERT INTO gioco VALUES('3','The last of us',' In una civiltà senza futuro, dove imperversano infetti e criminali, un uomo ormai segnato dalla vita, Joel, viene ingaggiato per condurre una ragazzina di 14 anni, Ellie, fino a una zona di quarantena militare. Ma quello che in principio sembra un incarico irrilevante, diventa presto un logorante viaggio attraverso gli Stati Uniti','59.99','2023-03-28','https://gaming-cdn.com/img/products/13298/pcover/1400x500/13298.jpg?v=1687775157','https://gaming-cdn.com/images/products/13298/616x353/the-last-of-us-part-i-pc-gioco-steam-europe-cover.jpg?v=1687775157','1','4','5');
INSERT INTO gioco VALUES('4','Grand theft auto V',"Grand Theft Auto V: Premium Edition comprende l'esperienza di gioco completa di Grand Theft Auto V, l'accesso gratuito a Grand Theft Auto Online, in evoluzione costante, e tutti gli aggiornamenti e i nuovi contenuti, come The Cayo Perico Heist, il Casinò e Resort Diamond, il Colpo al Casinò Diamond, Traffico d'armi e molto altro ancora.",'29.99','2015-04-14','https://gaming-cdn.com/img/products/4211/pcover/1400x500/4211.jpg?v=1652713683','https://gaming-cdn.com/images/products/4211/616x353/grand-theft-auto-v-premium-online-edition-premium-online-edition-pc-gioco-rockstar-cover.jpg?v=1652713683','1','4','2');
INSERT INTO gioco VALUES('5','Remnant',"Mondi inimmaginabili. Avversità incessanti In Remnant II, sequel del gioco best-seller Remnant: From the Ashes, gli ultimi sopravvissuti dell'umanità devono affrontare una schiera di nuovi boss sovrumani e creature letali, esplorando mondi terrificanti. Gioca in solitaria oppure in co-op con altri due amici e sfida gli abissi dell'ignoto per impedire a una forza malvagia di distruggere la realtà stessa.",'69.99','2023-06-28','https://gaming-cdn.com/themes/igv2/images/generic-background.png','https://gaming-cdn.com/images/products/14372/616x353/remnant-2-ultimate-edition-accesso-anticipato-ultimate-edition-pc-gioco-steam-cover.jpg?v=1686672879','1','6','7');
INSERT INTO gioco VALUES('6',"Tom Clancy's Rainbow Six Siege Deluxe Edition"," GameSpot Tom Clancy's Rainbow Six® Siege è uno sparatutto d'élite a squadre, tattico e realistico, in cui trionfano pianificazione ed esecuzione ad alto livello. È caratterizzato da un gameplay 5v5 attacco contro difesa e da intensi combattimenti ravvicinati in ambienti distruttibili" ,'29.99','2015-12-01','https://gaming-cdn.com/img/products/406/pcover/1400x500/406.jpg?v=1649421231','https://gaming-cdn.com/images/products/4891/616x353/tom-clancy-s-rainbow-six-siege-deluxe-edition-deluxe-edition-pc-gioco-ubisoft-connect-europe-cover.jpg?v=1671554414','1','7','3');
INSERT INTO gioco VALUES('7','Mortal Kombat 11 Ultimate',"Vesti i panni dei protettori della Terra in DUE storie avvincenti che sovvertono le leggi spazio-temporali e affronta una lotta contro il tempo per impedire a Kronika di riavviare la storia. Contiene l'elenco kompleto dei 37 kombattenti, inclusi gli ultimi arrivati: Rain, Mileena e Rambo. Include MK11, Kombat Pack 1, Espansione Aftermath e Kombat Pack 2.",'47.99','2020-11-17','https://gaming-cdn.com/img/products/8432/pcover/1400x500/8432.jpg?v=1674053729','https://gaming-cdn.com/images/products/8432/616x353/mortal-kombat-11-ultimate-ps4-ps5-ultimate-playstation-4-playstation-5-gioco-playstation-store-europe-cover.jpg?v=1674053729','2','7','8');
INSERT INTO gioco VALUES('8',"Assassin's Creed Valhalla:L'alba del Ragnarok","In Assassin's Creed Valhalla: L'alba del Ragnarok, l'espansione più ambiziosa nella storia della serie, Eivor affronterà il proprio destino nei panni di Odino, il dio norreno della guerra e della saggezza. Scatena i tuoi nuovi poteri divini in una disperata missione che ti porterà ad attraversare un universo mozzafiato.",'8.99','2022-03-10','https://gaming-cdn.com/img/products/10162/pcover/1400x500/10162.jpg?v=1657202715','https://gaming-cdn.com/images/products/10162/616x353/assassin-s-creed-valhalla-l-alba-del-ragnarok-ps4-playstation-4-gioco-playstation-store-europe-cover.jpg?v=1657202715','2','4','3');
INSERT INTO gioco VALUES('9','Horizon Forbidden West PS5',"Unisciti al viaggio di Aloy verso l'Ovest Proibito, una frontiera maestosa e pericolosa che nasconde nuove e misteriose minacce.Esplora terre remote, combatti contro macchine ancora più grandi e terrificanti e incontra nuove e stupefacenti tribù al tuo ritorno nel lontano futuro post-apocalittico di Horizon.La terra sta morendo. Violente tempeste e una piaga inarrestabile funestano quel poco che resta dell'umanità, mentre nuove e tremende macchine vanno a caccia lungo i confini. La vita sulla Terra sembra destinata a una nuova estinzione e nessuno ne conosce il motivo.",'36.99','2022-02-18','https://gaming-cdn.com/img/products/8893/pcover/1400x500/8893.jpg?v=1665495056','https://gaming-cdn.com/images/products/13049/616x353/horizon-forbidden-west-ps5-playstation-5-gioco-playstation-store-europe-cover.jpg?v=1679495048','2','6','9');
INSERT INTO gioco VALUES('10','God of War:Ragnarok PS5',"È in arrivo dagli sviluppatori di Santa Monica Studio il sequel dell’apprezzatissimo God of War (2018). Unisciti a Kratos e Atreus in un viaggio mitico alla ricerca di risposte prima che sopraggiunga il Ragnarök. Insieme, padre e figlio si spingeranno al limite nel corso del loro viaggio in ognuno dei nove regni. Attraverso paesaggi mitologici mozzafiato affronteranno terribili nemici come dèi norreni o mostri, preparandosi alla resa dei conti finale.",'53.99','2022-11-09','https://gaming-cdn.com/img/products/9312/pcover/1400x500/9312.jpg?v=1683626731','https://gaming-cdn.com/images/products/9312/616x353/god-of-war-ragnarok-ps5-playstation-5-gioco-playstation-store-europe-cover.jpg?v=1683626731','2','4','10');
INSERT INTO gioco VALUES('11','Just Dance 2023 Edition PS5',"Entrate in una nuova era della danza con Just Dance® 2023 Edition! Modalità multigiocatore online, opzioni di personalizzazione, coinvolgenti mondi 3D e nuovi brani e modalità di gioco aggiunti nel corso dell'anno: preparatevi a vivere una festa infinita! - Multigiocatore online: grazie a questa modalità inedita, ora potete giocare a Just Dance con chi volete ovunque voi siate! ",'21.99','2022-11-22','https://gaming-cdn.com/img/products/12863/pcover/1400x500/12863.jpg?v=1664291457','https://gaming-cdn.com/images/products/12864/616x353/just-dance-2023-edition-ps5-playstation-5-gioco-playstation-store-europe-cover.jpg?v=1669107741','2','8','3');
INSERT INTO gioco VALUES('12','Forza Horizon 5',"È il momento di FORZA HORIZON 5 RALLY ADVENTURE! Guida mostri da rally appositamente costruiti e conquista l'aspro territorio di Sierra Nueva. Unisciti a tre squadre di rally e affronta i percorsi più emozionanti mai visti in rally e gare Horizon. Vivi l'intensità degli enormi tracciati sterrati e delle strade trasformabili a bordo di 10 nuove auto e gustati le scoppiettanti fiammate dell'anti-latenza. ",'15.99','2023-03-29','https://gaming-cdn.com/img/products/8701/pcover/1400x500/8701.jpg?v=1681289108','https://gaming-cdn.com/images/products/13632/616x353/forza-horizon-5-rally-adventure-pc-xbox-one-xbox-series-x-s-pc-xbox-one-xbox-series-x-s-gioco-microsoft-store-cover.jpg?v=1687183783','3','9','11');
INSERT INTO gioco VALUES('13','Diablo IV Edition',"L'Ultimate Edition di Diablo® IV include: - Diablo® IV per Xbox One e Xbox Series X|S - Ali di Inarius e mascotte Inarius Murloc in Diablo® III* - Cavalcatura Amalgama dell'Ira in World of Warcraft®* - Set cosmetico Oscurità Alata Bruna in Diablo Immortal®* - Cavalcatura Tentazione in Diablo® IV** - Armatura cavalcatura Carapace Infernale in Diablo® IV** - Emote Ali del Creatore in Diablo® IV - Pass Battaglia stagionale accelerato sbloccato in Diablo® IV",'87.99','2023-06-06','https://gaming-cdn.com/img/products/13392/pcover/1400x500/13392.jpg?v=1686737491','https://gaming-cdn.com/images/products/13408/616x353/diablo-iv-ultimate-edition-xbox-one-xbox-series-x-s-ultimate-edition-xbox-series-x-s-xbox-one-gioco-microsoft-store-europe-cover.jpg?v=1686059464','3','4','12');
INSERT INTO gioco VALUES('14','Crash Team Rumble',"Quest'edizione include: - Crash Team Rumble per Xbox One / Xbox Series X|S - Sblocco Battle Pass Premium per la Stagione 1* Preparati a lanciarti, saltare, scivolare e rimbalzare in una nuova era di Crash. Crash Team Rumble porta Crash Bandicoot in una nuova direzione, con gli iconici eroi e antagonisti della serie che si affronteranno in sfide in team 4v4.",'24.99','2023-06-20','https://gaming-cdn.com/img/products/13336/pcover/1400x500/13336.jpg?v=1687271471','https://gaming-cdn.com/images/products/14232/616x353/crash-team-rumble-xbox-one-xbox-series-x-s-xbox-series-x-s-xbox-one-gioco-microsoft-store-cover.jpg?v=1687271594','3','4','13');
INSERT INTO gioco VALUES('15',"Assassin's Creed:Unity","Assassin s Creed Unity è un gioco di azione/avventura ambientato nella città di Parigi, durante uno dei suoi periodi più bui, la Rivoluzione Francese. Questa volta vestirai i panni del tuo eroe. Avrai pieno controllo di Arno, potendo personalizzare il suo equipaggiamento, sia visivamente, che meccanicamente. In aggiunta a un epica esperienza single-player, Assassin s Creed Unity offre la possibilità di giocare con altri tre amici in una campagna cooperativa online in svariate missioni. Prendi parte ad uno dei momenti cruciali della storia francese e immergiti in un avvincente trama e in un'ambientazione di gioco mozzafiato, quella che ha portato la Città delle Luci allo splendore dei giorni nostri.",'30.99','2014-11-13','https://gaming-cdn.com/img/products/595/pcover/1400x500/595.jpg?v=1650007681','https://gaming-cdn.com/images/products/595/616x353/assassin-s-creed-unity-xbox-one-xbox-series-x-s-xbox-one-xbox-series-x-s-gioco-microsoft-store-europe-cover.jpg?v=1650007681','3','7','3');
INSERT INTO gioco VALUES('16','F1 23',"Tieni il piede lontano dal freno in EA SPORTS™ F1® 23, il videogioco ufficiale del 2023 FIA Formula One World Championship. Questo gioco include la possibilità di acquistare, all’interno del gioco, tramite denaro reale una valuta virtuale da utilizzare per acquistare oggetti di gioco virtuali....",'63.99','2023-06-16','https://gaming-cdn.com/img/products/13660/pcover/1400x500/13660.jpg?v=1686902107','https://gaming-cdn.com/images/products/14072/616x353/f1-23-xbox-one-xbox-series-x-s-xbox-one-xbox-series-x-s-gioco-microsoft-store-cover.jpg?v=1686902915','3','5','4');
INSERT INTO gioco VALUES('17','The Legend Of Zelda:Tears of the Kingdom Switch',"Un epico viaggio attraverso Hyrule e i suoi cieli ti attende in The Legend of Zelda: Tears of the Kingdom per Nintendo Switch. Crea la tua avventura in un mondo dove potrai lasciare libero sfogo all'immaginazione. In questo seguito di The Legend of Zelda: Breath of the Wild sarai tu a decidere quale cammino seguire mentre esplori le sconfinate distese di Hyrule e le misteriose isole che fluttuano nei suoi vasti cieli. ",'69.99','2023-05-12','https://gaming-cdn.com/img/products/4860/pcover/1400x500/4860.jpg?v=1684751621','https://gaming-cdn.com/images/products/4860/616x353/the-legend-of-zelda-tears-of-the-kingdom-switch-switch-gioco-nintendo-eshop-europe-cover.jpg?v=1684751621','4','7','14');
INSERT INTO gioco VALUES('18',"Mario+Rabbids Kingdom Battle Switch","Due mondi molto diversi si scontrano in Mario + Rabbids® Kingdom Battle, una stravagante avventura strategica solo per Nintendo Switch. Forma un'improbabile squadra di eroi per riportare l'ordine nel Regno dei Funghi e affronta combattimenti a turni dinamici, ostacoli insidiosi e nemici imprevedibili.",'39.99','2017-08-29','https://gaming-cdn.com/img/products/8377/pcover/1400x500/8377.jpg?v=1650633334','https://gaming-cdn.com/images/products/8377/616x353/mario-rabbids-kingdom-battle-switch-switch-gioco-nintendo-eshop-europe-cover.jpg?v=1650633334','4','4','3');
INSERT INTO gioco VALUES('19','Dead Island 2 Gold Edition',"L'amatissima saga zombi ritorna con una formula unica di horror, umorismo dark e azione ammazzazombi esagerata, che dà vita a un'epica avventura pulp. Dead Island 2 è un RPG di azione in prima persona, elegante, vibrante e travolto dall'infezione zombi. Esplora una Los Angeles intrisa di sangue. Incontra personaggi fuori dall'ordinario. Fai strage di nemici con dettagli squisitamente cruenti.",'89.99','2023-04-21','https://gaming-cdn.com/img/products/398/pcover/1400x500/398.jpg?v=1685373574','https://gaming-cdn.com/images/products/13402/616x353/dead-island-2-gold-edition-xbox-one-xbox-series-x-s-gold-edition-xbox-series-x-s-xbox-one-gioco-microsoft-store-cover.jpg?v=1682064970','4','7','15');
INSERT INTO gioco VALUES('20',"Aliens: Dark Descendent","In Aliens: Dark Descent comandi una squadra di esperti Marine Coloniali per tentare di fermare l'insorgenza di terrificanti Xenomorfi sulla luna di Lethe. Guida i tuoi soldati in combattimenti in tempo reali contro gli iconici Xenomorfi, agenti deviati dell'insaziabile Weyland-Yutani Corporation e altre creature orribili mai apparse prima nel franchise di Alien. Sei tu che comandi. Loro sono le tue armi.",'39.99','2023-06-19','https://gaming-cdn.com/img/products/13838/pcover/1400x500/13838.jpg?v=1687272113','https://gaming-cdn.com/images/products/14231/616x353/aliens-dark-descent-xbox-one-xbox-series-x-s-xbox-one-xbox-series-x-s-gioco-microsoft-store-cover.jpg?v=1687272078','4','7','16');
INSERT INTO gioco VALUES('21','Pokemon Scarlatto',"Scopri storie inedite, esplora nuove aree e incontra nuovi personaggi e Pokémon con il DLC a pagamento Pokémon Scarlatto: Il tesoro dell'Area Zero! Parte I: La maschera turchese . Uscita prevista: autunno 2023 Partecipa a una gita scolastica nella placida Nordivia, i cui abitanti abitano alle pendici di una imponente montagna. Indossa un tradizionale abito jinbei, fai amicizia con nuovi personaggi e Pokémon e fai luce sulle leggende di questa terra.",'34.99','2023-02-27','https://gaming-cdn.com/img/products/10535/pcover/1400x500/10535.jpg?v=1677581145','https://gaming-cdn.com/images/products/13653/616x353/pokemon-scarlatto-il-tesoro-dell-area-zero-switch-switch-gioco-nintendo-eshop-europe-cover.jpg?v=1677663485','4','4','14');
INSERT INTO gioco VALUES('22',"Far Cry 6","Far Cry 6 per PC è ambientato nell'immaginaria isola caraibica di Yara, uno sparatutto in prima persona in un luogo open world. Il gioco vanta la più grande mappa di Far Cry fino ad oggi che puoi attraversare a piedi o in una gamma ben diversificata di veicoli e, grazie agli sforzi determinati del Presidente, il paradiso tropicale è congelato nel tempo. Questo per impedire alla popolazione di avere idee sull'indipendenza e su elezioni libere ed eque e altre simili sciocchezze.",'59.99','2021-08-17','https://gaming-cdn.com/img/products/7080/pcover/1400x500/7080.jpg?v=1666101212','https://gaming-cdn.com/images/products/7080/616x353/far-cry-6-pc-gioco-ubisoft-connect-europe-cover.jpg?v=1666101212','1','1','3');
INSERT INTO gioco VALUES('23',"Tom Clancy's Ghost Recon:Breakpoint","Tom Clancy s Ghost Recon: Breakpoint per PC è un gioco sparatutto tattico, l'undicesimo della serie Ghost Recon di Tom Clancy e un sequel diretto di TCGR: Wildlands. Per la prima volta nel franchise, l'impostazione del gioco non è radicata nella realtà poiché gli sviluppatori volevano avere più libertà nel creare diversi tipi di terreno e altre caratteristiche",'59.99','2019-10-04','https://gaming-cdn.com/img/products/4595/pcover/1400x500/4595.jpg?v=1650451967','https://gaming-cdn.com/images/products/4595/616x353/tom-clancy-s-ghost-recon-breakpoint-pc-gioco-ubisoft-connect-europe-cover.jpg?v=1650451967','1','1','3');
INSERT INTO gioco VALUES('24',"Far Cry Primal","Informazioni sul gioco Il premiato franchise di Far Cry, dopo aver visitato i tropici e l'Himalaya, si avventura nella lotta per la sopravvivenza agli albori dell'umanità, con il suo innovativo sistema di gioco in un mondo liberamente esplorabile, belve gigantesche, paesaggi mozzafiato e imprevedibili incontri nella natura selvaggia. Benvenuto nell'età della pietra, dove il pericolo è estremo e le avventure non conoscono limiti.",'5.99','2016-03-01','https://gaming-cdn.com/img/products/1084/pcover/1400x500/1084.jpg?v=1650481900','https://gaming-cdn.com/images/products/1084/616x353/far-cry-primal-pc-gioco-ubisoft-connect-cover.jpg?v=1650481900','1','1','3');
INSERT INTO gioco VALUES('25',"Call of Duty: Modern Warfare","Call of Duty: Modern Warfare per PC è stato pubblicato per la prima volta nel 2007, ma si è rivelato un gioco molto popolare e ben realizzato e la sua popolarità non si è mai esaurita. Recentemente rimasterizzato per sfruttare il miglior rendering e le interfacce grafiche, è un gioco sparatutto in prima persona ambientato in una realtà alternativa (anche se molto credibile come retroscena) ai giorni nostri, presentando l'assassinio di un presidente mediorientale che minaccia di sfociare in una guerra globale",'20.99','2019-10-25','https://gaming-cdn.com/img/products/4394/pcover/1400x500/4394.jpg?v=1674152565','https://gaming-cdn.com/images/products/4394/616x353/call-of-duty-modern-warfare-pc-gioco-cover.jpg?v=1674152565','2','1','7');
INSERT INTO gioco VALUES('26',"Minecraft:Java & Bedrock Edition","Crea, esplora, sopravvivi, ripeti. Minecraft: Java Edition e Bedrock Edition sono ora un unico pacchetto per Windows. Minecraft: Java & Bedrock Edition ti dà accesso a entrambi i giochi con un solo acquisto e un launcher unificato, semplificando al massimo il passaggio da un'edizione all'altra. Gioca in cross-play con qualsiasi giocatore di Minecraft semplicemente passando all'edizione dei tuoi amici. Ora puoi goderti il doppio dell'estrazione e il doppio della fabbricazione insieme al numero di giocatori di Minecraft più alto di sempre.",'21.99','2011-09-19','https://gaming-cdn.com/img/products/2369/pcover/1400x500/2369.jpg?v=1677838142','https://gaming-cdn.com/images/products/12567/616x353/minecraft-java-e-bedrock-edition-pc-gioco-europe-cover.jpg?v=1680508579','3','3','12');
INSERT INTO gioco VALUES('27',"The Elder Scrolls V:Skyrim VR","Sviluppato dai maestri di Bethesda Game Studios, Skyrim VR è un enorme gioco a mondo aperto che ripropone l'indimenticabile capolavoro fantasy con un livello di profondità, coinvolgimento e immediatezza che solo la realtà virtuale può offrire. Combatti antichi draghi, esplora aspre montagne e vivi liberamente moltissime altre avventure in Skyrim VR, che oltre al gioco base include anche tutti i DLC ufficiali: Dawnguard, Hearthfire e Dragonborn.",'14.99','2018-04-03','https://gaming-cdn.com/img/products/2511/pcover/1400x500/2511.jpg?v=1629464228','https://gaming-cdn.com/images/products/2511/616x353/the-elder-scrolls-v-skyrim-vr-vr-edition-pc-gioco-steam-cover.jpg?v=1629464228','2','3','12');
INSERT INTO gioco VALUES('28',"Superhoy VR","SUPERHOT VR è lo sparatutto in realtà virtuale che cancella il confine tra cauta strategia e massacro sfrenato, nel quale il tempo si muove solo quando ti muovi tu. Niente barre di salute rigeneranti. Niente munizioni piazzate dove serve. Ci sei solo tu, in inferiorità numerica, che afferri le armi cadute ai nemici per sparare, tagliare e muoverti attraverso un uragano di proiettili in slow-motion. ",'8.99','2017-05-25','https://gaming-cdn.com/img/products/3642/pcover/1400x500/3642.jpg?v=1649837756','https://gaming-cdn.com/images/products/3642/616x353/superhot-vr-vr-pc-gioco-steam-cover.jpg?v=1649837756','1','3','10');
INSERT INTO gioco VALUES('29',"Assetto Corsa Competizione","Il DLC 2023 GT World Challenge di Assetto Corsa Competizione ti porta al centro dell'azione della stagione 2023. Questo nuovo DLC introduce 3 nuove vetture e una pista famosa in tutto il mondo, il Circuito Ricardo Tormo Valencia. Il pacchetto DLC include. Ferrari 296 GT3 Porsche 911 (992) GT3 R Lamborghini Huracàn EVO2 Circuito Ricardo Tormo – Valencia I nuovi contenuti sono disponibili presso la sezione 'Open Series' delle stagioni dell'interfaccia grafica.",'9.99','2023-04-19','https://gaming-cdn.com/img/products/3153/pcover/1400x500/3153.jpg?v=1649405560','https://gaming-cdn.com/images/products/13993/616x353/assetto-corsa-competizione-2023-gt-world-challenge-pack-pc-gioco-steam-cover.jpg?v=1683290080','3','5','15');
INSERT INTO gioco VALUES('30',"DiRT Rally","DiRT Rally per PC è un videogioco di corse automobilistiche che simula la guida di rally. È un gioco completo con una vasta scelta di auto, percorsi e luoghi da scegliere. Informazioni sul gioco Il gioco inizia lontano da qualsiasi strada o tracciato mentre scegli e personalizzi la tua auto. Inizialmente ci sono diciassette veicoli tra cui scegliere che raddoppiano con l’aggiunta dei vari componenti aggiuntivi e i pacchetti di espansione.",'15.99','2015-12-01','https://gaming-cdn.com/img/products/514/pcover/1400x500/514.jpg?v=1662469663','https://gaming-cdn.com/images/products/514/616x353/dirt-rally-pc-mac-gioco-steam-cover.jpg?v=1662469663','1','5','2');
INSERT INTO gioco VALUES('31',"Shadows of Doubt","Un gioco stealth sandbox generato proceduralmente con un'intera città piena di segreti da esplorare! Shadows of Doubt è ambientato in una realtà alternativa negli anni '80 iperindustrializzati. Pensa come un detective e usa una serie di gadget come investigatore privato, raccogli prove e guadagni soldi risolvendo casi, trova e vendi informazioni e molto altro ancora.",'20.99','2023-04-24','https://gaming-cdn.com/img/products/13871/pcover/1400x500/13871.jpg?v=1683705538','https://gaming-cdn.com/images/products/13871/616x353/shadows-of-doubt-pc-gioco-steam-cover.jpg?v=1683705538','2','6','16');
INSERT INTO gioco VALUES('32',"Smalland:Survive the Wilds","Attraversa pozzanghere grandi come laghi, scala alberi imponenti come grattacieli, valica crepe nelle strade come fossero burroni, mentre vivi un enorme mondo open world da una nuova prospettiva. Esplora fitte foreste, paludi pericolose e strane rovine dei tempi antichi. Scopri le storie e le conoscenze dei PNG nascosti in tutto il mondo e impara a sopravvivere in questo deserto sconfinato. ",'15.99','2023-03-29','https://gaming-cdn.com/img/products/8256/pcover/1400x500/8256.jpg?v=1684147804','https://gaming-cdn.com/images/products/8256/616x353/smalland-survive-the-wilds-pc-gioco-steam-cover.jpg?v=1684147804','4','6','13');
INSERT INTO gioco VALUES('33',"Ride 5","Scalda le gomme e preparati a scendere in pista con RIDE 5. Immergiti in un'esperienza di gioco tanto adrenalinica quanto autentica, al punto che ti sembrerà davvero di sfrecciare sulla strada. Ritrova i tuoi modelli preferiti e scoprine di nuovi nel gioco di motociclismo per eccellenza! Corri su oltre 35 tracciati e colleziona più di 200 moto dei marchi più famosi al mondo, realizzate con un livello di dettaglio tale da darti l'impressione di montare in sella su un vero bolide",'41.99','2023-06-24','https://gaming-cdn.com/img/products/13417/pcover/1920x620/13417.jpg?v=1682084434','https://gaming-cdn.com/images/products/13417/616x353/ride-5-pc-gioco-steam-cover.jpg?v=1682084434','3','9','6');
INSERT INTO gioco VALUES('34',"MotoGP 19","MotoGP19 celebra la passione per i motori! Il gioco ufficiale del campionato motociclistico più amato al mondo torna con un nuovo capitolo ricco di novità!CONTENUTI UFFICIALI 2019Tutto il brivido della stagione 2019 direttamente a casa tua! Corri con tutti i piloti ufficiali delle categorie MotoGP, Moto2, Moto3, Red Bull MotoGP Rookies Cup e della nuova MotoE su 19 diversi tracciati.",'9.99','2019-06-06','https://gaming-cdn.com/img/products/4205/pcover/1920x620/4205.jpg?v=1650959470','https://gaming-cdn.com/images/products/4205/616x353/motogp-19-pc-gioco-steam-cover.jpg?v=1650959470','1','9','6');
INSERT INTO gioco VALUES('35',"Injustice 2 Legendary Edition","Potenzia e costruisci la versione definitiva delle tue leggende DC preferite in INJUSTICE 2, vincitore del miglior gioco di combattimento di IGN del 2017. TUTTI I PERSONAGGI DEL CONTENUTO SCARICABILE: include 10 personaggi aggiuntivi e 5 skin Premiere, tra cui Hellboy e TMNT.  OGNI BATTAGLIA TI DEFINISCE: a ogni partita guadagnerai equipaggiamento per equipaggiare, personalizzare ed evolvere il tuo roster.",'15.99','2018-03-27','https://gaming-cdn.com/img/products/1525/pcover/1920x620/1525.jpg?v=1652881682','https://gaming-cdn.com/images/products/2757/616x353/injustice-2-legendary-edition-legendary-edition-pc-gioco-steam-cover.jpg?v=1680623904','2','7','8');
INSERT INTO gioco VALUES('36',"Mortal Kombat 11 Kombat Pack2","Il Kombat Pack 2 include i kombattenti Mileena e Rain e l'iconico ospite Rambo, con l'aspetto e la voce dell'attore Sylvester Stallone. Rambo Rambo, ex soldato delle Forze Speciali tormentato dai ricordi del periodo di servizio in Vietnam, è duro, aggressivo e famoso nell'affrontare pericolose missioni da solo. Ora sfoggia le sue abilità brutali in Mortal Kombat. Mileena Mileena è il mix perfetto tra la ferocia di Baraka e la grazia di Kitana. ",'4.99','2020-11-17','https://gaming-cdn.com/img/products/3339/pcover/1920x620/3339.jpg?v=1649408755','https://gaming-cdn.com/images/products/8311/616x353/mortal-kombat-11-kombat-pack-2-pc-gioco-steam-cover.jpg?v=1652714866','3','7','8');



